services:
  app:
    build:
      context: ./back
    container_name: rachelle-arts-api
    volumes:
      - ./back:/var/www/back
    networks:
      - rachelle-network

  client:
    build:
      context: ./front
    container_name: rachelle-arts-front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    networks:
      - rachelle-network

  db:
    image: mysql:8.0
    container_name: rachelle-arts-db
    environment:
      MYSQL_DATABASE: rachelle_arts
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rachelle-network

networks:
  rachelle-network:
    driver: bridge